package garden;

/**
 * Pollen Class.  Pollen is generated by flowers, stored by gardens and consumed by Bees!
 */
public class Pollen {
    
    public int number;

    /**
     * Pollen constructor
     * @param integer number of Pollen grain!
     */
    public Pollen(int integer) {
        number = integer;
    }

    /**
     * Print pollen
     * @return string to pring
     */
    public String print() {
        return Integer.toString(number);
    }

}
